name: Rotate Script Key

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate new key and update file
        run: |
          RANDOM_PART=$(head /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 6)
          NEW_KEY="Empaxis-Free-$RANDOM_PART"
          
          echo "CURRENT_KEY=$NEW_KEY" >> $GITHUB_ENV
          
          FILE_PATH="HoholWare-Main" 
          sed -i "s/local CORRECT_KEY = \".*\"/local CORRECT_KEY = \"$NEW_KEY\"/" $FILE_PATH
          
          echo "Новый сгенерированный ключ: $NEW_KEY"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "Изменений нет."
          else
            git commit -m "Автоматическое обновление ключа лицензии [skip ci]"
            git push
          fi

            - name: Send New Key to Telegram
        run: |
          echo "Ожидаем 5 минут (300 секунд), чтобы обновился кэш GitHub RAW..."
          sleep 300
          
          CHAT_ID="@Empaxis_key"
          MESSAGE="🔑 *Обновлен ключ для Empaxis Beta\!*%0A%0AНовый ключ: \`${{ env.CURRENT_KEY }}\`%0A%0A_Ключ обновляется автоматически каждые 12 часов\._"
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=$MESSAGE" \
            -d "parse_mode=MarkdownV2"

